resolver: lts-11.2

docker:
  enable: false
  repo: fpco/stack-build:lts-11.2
  auto-pull: true

system-ghc: false

packages:
- .

extra-deps:
- unordered-containers-0.2.9.0
- aeson-1.3.0.0
- aeson-better-errors-0.9.1.0
- text-1.2.3.0
- bytestring-0.10.8.2
- vector-0.12.0.1
- turtle-1.5.7
- optparse-applicative-0.14.2.0
- directory-1.3.2.2
- transformers-0.5.5.0
- hspec-2.5.0
- hspec-core-2.5.0
- hspec-discover-2.5.0
