// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var Main = 0;

var Print = 0;

var Types = 0;

exports.Main = Main;
exports.Print = Print;
exports.Types = Types;
/* No side effect */
