// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Block = require("bs-platform/lib/js/block.js");
var Decode$BorderTypes = require("../src/Decode.bs.js");

describe("Decode", (function () {
        describe("Primitive", (function () {
                return Jest.test("to decode string type", (function () {
                              return Jest.Expect[/* toEqual */12](/* Ok */Block.variant("Ok", 0, [/* String */0]), Jest.Expect[/* expect */0](Decode$BorderTypes.Primitive[/* decode */9]("string")));
                            }));
              }));
        return /* () */0;
      }));

var R = 0;

exports.R = R;
/*  Not a pure module */
