// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/lib/js/src/Json.bs.js");
var Decode$BorderTypes = require("./Decode.bs.js");

var result = Decode$BorderTypes.Primitive[/* decode */9](Json.parseOrRaise("[55, \"string\"]"));

console.log(result);

exports.result = result;
/* result Not a pure module */
