// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Map = require("bs-platform/lib/js/map.js");
var Block = require("bs-platform/lib/js/block.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var compare = Caml_obj.caml_compare;

var StringMap = $$Map.Make(/* module */Block.localModule(["compare"], [compare]));

exports.StringMap = StringMap;
/* StringMap Not a pure module */
