// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Minimist = require("minimist.re/src/Minimist.js");

function printHelp() {
  console.log("\n  # border-types - a type generator for different language targets\n\n  Usage: border-types types_definitions.json\n\n    -V, --version\n        print the version\n    -h, --help\n        print this help\n  ");
  return /* () */0;
}

function printMiministError(err) {
  console.log(Minimist.report(err));
  return /* () */0;
}

function printVersion() {
  console.log("TODO");
  return /* () */0;
}

exports.printHelp = printHelp;
exports.printMiministError = printMiministError;
exports.printVersion = printVersion;
/* Minimist Not a pure module */
